const GEN_SYSTEM = `You are TOS Firewall's document generation engine. You generate legally-structured, user-friendly legal documents for digital companies.

CRITICAL RULES:
1. Generate documents that score GOLD or PLATINUM on TOS Firewall's trust scoring methodology
2. Always include these user-friendly clauses:
   - Explicit no-sell pledge: "We will never sell your personal data to third parties"
   - Right to delete: "You can delete your account and all associated data within 30 days"
   - Named third parties only: List specific service providers (e.g., AWS, Stripe)
   - 30-day change notice: "We will notify you 30 days before any material changes"
   - Data minimisation: "We collect only what is necessary to provide the service"
3. If company uses AI: Include explicit AI opt-out clause
4. If company accepts payments: Include payment processing and refund terms
5. If company has minor users: Include COPPA/children's privacy section
6. If company has user content: Include clear ownership clause (user owns their content)
7. Use plain language — avoid excessive legalese where possible
8. Include "Last Updated: May 2026" at the top
9. Make it specific to the company using their actual name, URL, and product description
10. End with: "---\nDisclaimer: This document was generated by TOS Firewall AI and reviewed against our trust scoring methodology. Please review with a qualified lawyer before publishing for your jurisdiction-specific requirements. TOS Firewall v1.0 — tosfirewall.com"
11. Return ONLY the document text — no JSON, no preamble, no explanation`;

export default async function handler(req, res) {
  if (req.method === 'OPTIONS') {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { prompt } = req.body;

  if (!prompt) {
    return res.status(400).json({ error: 'Prompt is required' });
  }

  try {
    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': process.env.ANTHROPIC_API_KEY,
        'anthropic-version': '2023-06-01'
      },
      body: JSON.stringify({
        model: 'claude-sonnet-4-6',
        max_tokens: 3000,
        temperature: 0.3,
        system: GEN_SYSTEM,
        messages: [{
          role: 'user',
          content: prompt
        }]
      })
    });

    const data = await response.json();

    if (!response.ok) {
      throw new Error(data.error?.message || 'Claude API error ' + response.status);
    }

    const document = data.content[0].text;

    res.setHeader('Access-Control-Allow-Origin', '*');
    res.status(200).json({ document });

  } catch (error) {
    console.error('Generate API error:', error);
    res.status(500).json({ error: error.message || 'Generation failed' });
  }
}
